# Generated by Django 3.0.6 on 2020-06-15 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=80)),
                ('street_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.City')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=40)),
                ('shop_house_id', models.IntegerField()),
                ('shop_time_to_open', models.TimeField()),
                ('shop_time_to_close', models.TimeField()),
                ('shop_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.City')),
                ('shop_street_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Street')),
            ],
        ),
    ]
